const String baseUrl = 'https://api.uiniqu.cloud/api/v1';

class auth {
  static const login = '/login';
  static const register = '/register';
}

const surah_list = [
  "Al Fatihah",
  "Al Baqarah",
  "Ali Imran",
  "An Nisaa",
  "Al Maidah",
  "Al An'am",
  "Al A'raf",
  "Al Anfaal",
  "At Taubah",
  "Yunus",
  "Huud",
  "Yusuf",
  "Ar Ra'du",
  "Ibrahim",
  "Al Hijr",
  "An Nahl",
  "Al Israa'",
  "Al Kahfi",
  "Maryam",
  "Thaahaa",
  "Al Anbiyaa",
  "Al Hajj",
  "Al Mu'minun",
  "An Nuur",
  "Al Furqaan",
  "Asy Syu'ara",
  "An Naml",
  "Al Qashash",
  "Al 'Ankabut",
  "Ar Ruum",
  "Luqman",
  "As Sajdah",
  "Al Ahzab",
  "Saba'",
  "Faathir",
  "Yaa Siin",
  "Ash Shaaffat",
  "Shaad",
  "Az Zumar",
  "Al Ghaafir",
  "Al Fushilat",
  "Asy Syuura",
  "Az Zukhruf",
  "Ad Dukhaan",
  "Al Jaatsiyah",
  "Al Ahqaaf",
  "Muhammad",
  "Al Fath",
  "Al Hujuraat",
  "Qaaf",
  "Adz Dzaariyaat",
  "Ath Thuur",
  "An Najm",
  "Al Qamar",
  "Ar Rahmaan",
  "Al Waaqi'ah",
  "Al Hadiid",
  "Al Mujaadalah",
  "Al Hasyr",
  "Al mumtahanah",
  "Ash Shaff",
  "Al Jumuah",
  "Al Munafiqun",
  "Ath Taghabun",
  "Ath Thalaaq",
  "At Tahriim",
  "Al Mulk",
  "Al Qalam",
  "Al Haaqqah",
  "Al Ma'aarij",
  "Nuh",
  "Al Jin",
  "Al Muzammil",
  "Al Muddastir",
  "Al Qiyaamah",
  "Al Insaan",
  "Al Mursalaat",
  "An Naba'",
  "An Naazi'at",
  "'Abasa",
  "At Takwiir",
  "Al Infithar",
  "Al Muthaffifin",
  "Al Insyiqaq",
  "Al Buruuj",
  "Ath Thariq",
  "Al A'laa",
  "Al Ghaasyiah",
  "Al Fajr",
  "Al Balad",
  "Asy Syams",
  "Al Lail",
  "Adh Dhuhaa",
  "Asy Syarh",
  "At Tiin",
  "Al 'Alaq",
  "Al Qadr",
  "Al Bayyinah",
  "Az Zalzalah",
  "Al 'Aadiyah",
  "Al Qaari'ah",
  "At Takaatsur",
  "Al 'Ashr",
  "Al Humazah",
  "Al Fiil",
  "Quraisy",
  "Al Maa'uun",
  "Al Kautsar",
  "Al Kafirun",
  "An Nashr",
  "Al Lahab",
  "Al Ikhlash",
  "Al Falaq",
  "An Naas"
];
